// Get the container where biographies will appear
const bioList = document.getElementById('bioList');

// Main function to load all biographies
async function loadBiographies() {
  try {
    // Fetch the index.json file generated by the GitHub Action
   const listResponse = await fetch("index.json");
    if (!listResponse.ok) throw new Error("Cannot load index.json");

    const fileList = await listResponse.json();

    // If the JSON is empty or invalid
    if (!Array.isArray(fileList) || fileList.length === 0) {
      bioList.innerHTML = "<p>No biographies available yet.</p>";
      return;
    }

    // Loop through all the .txt files listed in index.json
    for (const filePath of fileList) {
      try {
        const response = await fetch(filePath);
        if (!response.ok) throw new Error(`Failed to load ${filePath}`);
        const text = await response.text();

        // Create a card for each biography
        const card = document.createElement('div');
        card.className = 'bio-card';

        // Extract just the file name for the title
        const filename = filePath.split('/').pop().replace('.txt', '');

        card.innerHTML = `
          <h3>${filename.toUpperCase()}</h3>
          <pre>${text}</pre>
        `;

        bioList.appendChild(card);

      } catch (err) {
        console.error(`Error loading ${filePath}:`, err);
      }
    }
  } catch (err) {
    console.error("Error loading biography list:", err);
    bioList.innerHTML = "<p>⚠️ Error loading biographies. Please try again later.</p>";
  }
}

// Run the function on page load
loadBiographies();
